#!/bin/sh

echo "Starting with Thoughtbot base configuration..."
. ./mac

echo
echo "Continuing with OMC specific tools and services..."

brew bundle --file=- <<EOF
cask "java"
cask "chefdk"

brew "elasticsearch"
brew "memcached"
brew "zookeeper"
brew "gh"
brew "watch"
brew "pdsh"
brew "siege"

brew "maven"
brew "gradle"
brew "ant"
EOF
echo

# AWS credential stuff
echo "Requesting sudo for 'easy_install pip'"
sudo easy_install pip
echo "Requesting sudo for 'pip install awscli'"
sudo pip install awscli

gem_install_or_update "aws-keychain-util"
gem_install_or_update "aws-sdk-v1"
gem_install_or_update "hookup"

# Elixir and Phoenix
yes | mix local.hex

# Install Pow
if [ ! -f /Library/LaunchDaemons/cx.pow.firewall.plist ]; then
  curl get.pow.cx | sh
fi

# Install latest JRuby, Rubinius
find_latest_other_ruby() {
  other="$1"
  rbenv install -l | grep ${other} | tail -1 | sed -e 's/^ *//'
}
for platform in jruby rbx; do
  ruby_version="$(find_latest_other_ruby ${platform})"
  if ! rbenv versions | grep -Fq "${ruby_version}"; then
    RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/opt/openssl rbenv install -s "${ruby_version}"
  fi
done

# Install Yarn JS package manager
command -v yarn >/dev/null 2>&1 || {
  echo "Installing Yarn for Javascript package management"
  npm install -g yarn
}

# OS X: check for updates daily
if [ $(defaults read com.apple.SoftwareUpdate ScheduleFrequency) != "1" ]; then
  defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1
fi
