#!/bin/sh

echo "Installing XCode tools (ignore any errors)..."
xcode-select --install

echo "Starting with Thoughtbot base configuration..."
. ./mac

echo
echo "Continuing with OMC specific tools and services..."

brew bundle --file=- <<EOF
cask "java8"
cask "chefdk"

brew "elasticsearch"
brew "elixir"
brew "memcached"
brew "zookeeper"
brew "hub"
brew "watch"
brew "pdsh"
brew "siege"

brew "maven"
brew "gradle"
brew "ant"

brew "awscli"
brew "shellcheck"

# Version managers
brew "rbenv"   # Ruby
brew "nodenv"  # Node

EOF
echo

gem_install_or_update "aws-keychain-util"
gem_install_or_update "aws-sdk-v1"
gem_install_or_update "hookup"

# Elixir and Phoenix
yes | mix local.hex

# Install Pow
if [ ! -f /Library/LaunchDaemons/cx.pow.firewall.plist ]; then
  curl get.pow.cx | sh
fi

# Install Rubies
rbenv init
rbenv install 2.6.6 # Bonsai
rbenv install 2.4.9 # Websolr

# Install Yarn JS package manager
command -v yarn >/dev/null 2>&1 || {
  echo "Installing Yarn for Javascript package management"
  npm install -g yarn
}

# OS X: check for updates daily
defaults read com.apple.SoftwareUpdate ScheduleFrequency
if [ "$?" != "0" ]; then
  # com.apple.SoftwareUpdate is not set. Create it with a val of 1:
  echo "Creating key com.apple.SoftwareUpdate"
  defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1
elif [ $(defaults read com.apple.SoftwareUpdate ScheduleFrequency) != "1" ]; then
  defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1
fi

# Install Nix
curl -L https://nixos.org/nix/install | sh
