#!/bin/sh

echo "Starting with Thoughtbot base configuration..."
. ./mac

echo
echo "Continuing with OMC specific tools and services..."

brew bundle --file=- <<EOF
cask "java"
cask "chefdk"

brew "elasticsearch"
brew "memcached"
brew "zookeeper"
brew "gh"
brew "watch"
brew "pdsh"
brew "siege"
brew "elixir"

brew "maven"
brew "gradle"
brew "ant"
EOF
echo

# AWS credential stuff
echo "Requesting sudo for 'easy_install pip'"
sudo easy_install pip
echo "Requesting sudo for 'pip install awscli'"
sudo pip install awscli

gem_install_or_update "aws-keychain-util"
gem_install_or_update "aws-sdk-v1"
gem_install_or_update "hookup"

# Elixir and Phoenix
yes | mix local.hex

# Install Pow
if [ ! -f /Library/LaunchDaemons/cx.pow.firewall.plist ]; then
  curl get.pow.cx | sh
fi
